name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: luacheck lua/

  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.1.0
          args: --check lua/

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies
        run: |
          # Install busted dependencies manually to avoid lua-term issue
          luarocks install lua_cliargs
          luarocks install luasystem
          luarocks install dkjson
          luarocks install say
          luarocks install luassert
          luarocks install penlight
          luarocks install mediator_lua
          # Install busted without lua-term
          luarocks install busted --deps-mode=none
          # plenary.nvim is not available on luarocks

      - name: Run tests
        run: busted tests/test_*.lua --exclude-tags=integration

  neovim-integration:
    name: Neovim Integration Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: ["v0.10.0", "nightly"]
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install plenary.nvim
        run: |
          # Install plenary as a dependency
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim

      - name: Run integration tests
        run: |
          # Create minimal init.lua for testing
          cat > minimal_init.lua << EOF
          -- Add current plugin to runtimepath
          vim.opt.runtimepath:prepend(".")
          
          -- Set up packpath for plenary
          vim.opt.packpath:prepend("~/.local/share/nvim/site")
          
          -- Disable swapfiles for testing
          vim.opt.swapfile = false
          
          -- Load the integration test
          vim.cmd("source tests/integration_test.lua")
          EOF
          
          # Run Neovim with the integration test
          nvim --headless -u minimal_init.lua
